config/routes.rb
OmniauthTutorial::Application.routes.draw do

  root :to => "home#index"

  get   '/login', :to => 'sessions#new', :as => :login

  match '/auth/:provider/callback', :to => 'home#index'

  match '/auth/failure', :to => 'sessions#failure'

  get '/logout', :to => 'sessions#destroy'

  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id
  belongs_to :user
  validates :provider, :uid, :presence => true

 def self.find_or_create(auth_hash)
  unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    user = User.create :name => auth_hash["user_info"]["name"], :email => auth_hash["user_info"]["email"]
    auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  end
 
  auth
 end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :authorizations
  validates :name, :email, :presence => true
  def add_provider(auth_hash)
    # Check if the provider already exists, so we don't add it twice
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    auth_hash = request.env['omniauth.auth']
   if !auth_hash.blank?
    @authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    if @authorization
     #render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
     redirect_to root_url :notice => 'Signed In'
    else
     user = User.new :name => auth_hash["info"]["name"], :email => auth_hash["info"]["email"]
     user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
     user.save
     session[:user_id] = user.id
     #render :text => "Hi #{user.name}! You've signed up."
     redirect_to root_url :notice => 'Signed Up'
    end
   end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth_hash = request.env['omniauth.auth']
    @authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    if @authorization
     render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
    else
     user = User.new :name => auth_hash["info"]["name"], :email => auth_hash["info"]["email"]
     user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
     user.save
     session[:user_id] = user.id
    render :text => "Hi #{user.name}! You've signed up."
   end
  end

  def destroy
    session[:user_id] = nil
    render :text => "You've logged out!"
  end

  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:fb="https://www.facebook.com/2008/fbml">

<head>
    
</head>
<body>
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/en_US/all.js"></script>

    <center>
        <h1>Facebook Demo Send Invetation Application</h1>

            <% if current_user %>
                Welcome <%= current_user.name %>!
                <% button_to "Sign Out", signout_path  %>
            <% else %>
                <% button_to "Sign In with Facebook", "/auth/facebook" %>
            <% end %>

    <p>
    <input type="button"
      onclick="sendRequestViaMultiFriendSelector(); return false;"
      value="Send Request To Your Facebook Friends"
    />
    </p>
    
   </center>

    <script>
      FB.init({
        appId  : '352901268149640',
        frictionlessRequests: true
      });

      function sendRequestToRecipients() {
        var user_ids = document.getElementsByName("user_ids")[0].value;
        FB.ui({method: 'apprequests',
          message: 'Awesome Application try it once',
          to: user_ids
        }, requestCallback);
      }

      function sendRequestViaMultiFriendSelector() {
        FB.ui({method: 'apprequests',
          message: 'Awesome application try it once'
        }, requestCallback);
      }
      
      function requestCallback(response) {
        // Handle callback here
      }
    </script>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmniauthTutorial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>